.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. freecoin_qt test_freecoin_qt
clean: FORCE
	$(MAKE) -C .. freecoin_qt_clean test_freecoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_freecoin_qt_check
freecoin-qt freecoin-qt.exe: FORCE
	 $(MAKE) -C .. freecoin_qt
